### ISSUE TITLE
Calling `create` method twice in a row results in a URI collision error

### ISSUE THREAD

**Issue by bbartley** [llotneb/SBOL#116]
Calling `create` method twice in a row appears to create a URI collision:
```
>>> doc = Document()
>>> comp1 = doc.componentDefinitions.create('cd1')
>>> comp2 = doc.componentDefinitions.create('cd2')
WARNING:rdflib.term:The object http://examples.org/ComponentDefinition/cd2/1 is already contained by the http://sbols.org/v2#ComponentDefinition does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:The object http://examples.org/ComponentDefinition/cd2/1 is already contained by the http://sbols.org/v2#ComponentDefinition property does not look like a valid URI, trying to serialize this will break.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bbartley/Dev/git/SBOL/sbol/property.py", line 423, in create
    self.add(obj)
  File "/Users/bbartley/Dev/git/SBOL/sbol/property.py", line 436, in add
    SBOLErrorCode.SBOL_ERROR_URI_NOT_UNIQUE)
sbol.sbolerror.SBOLError: (rdflib.term.URIRef('The object http://examples.org/ComponentDefinition/cd2/1 is already contained by the http://sbols.org/v2#ComponentDefinition property'), <SBOLErrorCode.SBOL_ERROR_URI_NOT_UNIQUE: 17>)
```
However,  inspecting the CDs contained in the Document indicates that there shouldn't be a collision:
```
>>> for cd in doc.componentDefinitions:
...     print(cd)
... 
http://examples.org/ComponentDefinition/cd1/1
```
The error generalizes to `Document.sequences` and other object container properties as well.

**Comment by tcmitchell** [comment]
This works for me. I think this is a duplicate of #62. Can you please test against the current master branch?

You may be working with a very out of date tree.

```python
>>> import sbol
INFO:rdflib:RDFLib Version: 4.2.2
>>> doc = sbol.Document()
>>> comp1 = doc.componentDefinitions.create('cd1')
>>> comp2 = doc.componentDefinitions.create('cd2')
>>> for cd in doc.componentDefinitions:
...     print(cd)
... 
http://examples.org/ComponentDefinition/cd1/1
http://examples.org/ComponentDefinition/cd2/1
>>> 
```

**Comment by bbartley** [comment]
Confirmed.
