### ISSUE TITLE
AttributeError: 'ModuleDefinition' object has no attribute 'mapsTos'

### ISSUE THREAD

**Issue by bbartley** [llotneb/SBOL#121]
Also, related:
```
>>> m = MapsTo('m')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'MapsTo' is not defined
```

**Comment by tcmitchell** [comment]
pySBOL ModuleDefinition's do not have a mapsTos property either:

```
>>> import sbol
>>> md = sbol.ModuleDefinition('md1')
>>> md.mapsTos
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/sbol/libsbol.py", line 8976, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, ModuleDefinition, name)
  File "/usr/local/lib/python3.6/dist-packages/sbol/libsbol.py", line 89, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'ModuleDefinition' object has no attribute 'mapsTos'
>>> 
```

Was this exception from a program that uses pySBOL?
