### ISSUE TITLE
Prevent overwriting OwnedObjects through __getattribute__ and __setattr__

### ISSUE THREAD

**Issue by tcmitchell** [llotneb/SBOL#124]
It is easy for a user to overwrite an OwnedObject attribute with another value:

```python
>>> import sbol
INFO:rdflib:RDFLib Version: 4.2.2
>>> md = sbol.ModuleDefinition()
>>> type(md.modules)
<class 'sbol.property.OwnedObject'>
>>> m = sbol.Module()
>>> m
<sbol.module.Module object at 0x7fcd48cd0358>
>>> md.modules = [m]
>>> type(md.modules)
<class 'list'>
```

Use `SBOLObject.__getattribute__` and `SBOLObject.__setattr__` for OwnedObject attributes as we have done for ReferencedObject attributes.

**Comment by tcmitchell** [comment]
Given the availability and likely use of OwnedObject methods like `get()` and `find()`, we probably do not want to override `__getattribute__` for Owned Objects. We could still use `__setattr__` to prevent overwriting the attribute.

There are other problems with OwnedObjects as well:

```python
>>> import sbol
INFO:rdflib:RDFLib Version: 4.2.2
>>> md = sbol.ModuleDefinition('md')
>>> m1 = sbol.Module('m1')
>>> md.modules.set([m1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/SBOL/sbol/property.py", line 612, in set
    if self._isHidden() and doc.find(sbol_obj.identity):
  File "/SBOL/sbol/property.py", line 218, in _isHidden
    return self._rdf_type in self._sbol_owner.hidden_properties
  File "/SBOL/sbol/object.py", line 396, in __getattribute__
    result = object.__getattribute__(self, name)
AttributeError: 'ModuleDefinition' object has no attribute 'hidden_properties'
```

Fixing that yields a document issue, probably because this particular ModuleDefinition has no document.
