### ISSUE TITLE
OwnedObject.create does not add the new object to the collection

### ISSUE THREAD

**Issue by tcmitchell** [llotneb/SBOL#35]
This underlies a bunch of code, including assemble().

In pySBOL:

```python
>>> import sbol
>>> doc = sbol.Document()
>>> md = doc.moduleDefinitions.create('thing1')
>>> md.identity
'http://examples.org/ModuleDefinition/thing1/1'
>>> len(md.modules)
0
>>> md.modules.create('thing2')
Module
>>> len(md.modules)
1
```

But in SBOL, that last `len` call results in zero.

**Comment by tcmitchell** [comment]
Here is a simpler case that should not result in an error.

With SBOL (this repo):

```python
>>> import sbol
INFO:rdflib:RDFLib Version: 4.2.2
>>> doc = sbol.Document()
>>> thing = doc.moduleDefinitions.create('thing1')
>>> md = doc.moduleDefinitions.get(thing.identity)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tommy/sd2/SBOL/sbol/property.py", line 533, in get
    return self.__getitem__(uri)
  File "/home/tommy/sd2/SBOL/sbol/property.py", line 443, in __getitem__
    return self.get_uri(id)
  File "/home/tommy/sd2/SBOL/sbol/property.py", line 488, in get_uri
    SBOLErrorCode.NOT_FOUND_ERROR)
sbol.sbolerror.SBOLError: ('Object http://examples.org/ModuleDefinition/thing1/1 not found', <SBOLErrorCode.NOT_FOUND_ERROR: 2>)
```

Now in pySBOL:

```python
>>> import sbol
>>> doc = sbol.Document()
>>> thing = doc.moduleDefinitions.create('thing1')
>>> md = doc.moduleDefinitions.get(thing.identity)
>>> md.identity
'http://examples.org/ModuleDefinition/thing1/1'
```
