### ISSUE TITLE
AttributeError: 'PartShop' object has no attribute 'getURL'

### ISSUE THREAD

**Issue by tcmitchell** [llotneb/SBOL#42]
Testing compatibility with etl-to-synbiohub-pipeline yields errors because PartShop does not have a `getURL()` method.

```
======================================================================
ERROR: setUpClass (test_sbh_submissions.TestBackBuilder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/etsp/tests/test_sbh_submissions.py", line 23, in setUpClass
    test.sparql_endpoint = SynBioHubQuery(test.sbh.getURL() + '/sparql', False, test.sbh.getUser(),
AttributeError: 'PartShop' object has no attribute 'getURL'
```
```
======================================================================
ERROR: setUpClass (test_sbh_submissions.TestOrphans)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/etsp/tests/test_sbh_submissions.py", line 59, in setUpClass
    test.sparql_endpoint = SynBioHubQuery(test.sbh.getURL() + '/sparql', False, test.sbh.getUser(),
AttributeError: 'PartShop' object has no attribute 'getURL'
```

**Comment by bbartley** [comment]
Related: AttributeError: 'PartShop' object has no attribute 'getKey'

**Comment by bbartley** [comment]
This was an easy fix and it was blocking me, so I went ahead and fixed it.  See PR #47
