### ISSUE TITLE
Sequence encodings should be URIRefs

### ISSUE THREAD

**Issue by tcmitchell** [llotneb/SBOL#46]
One of the SYNBICT unit tests (see below for which one) triggers an IndexError in OwnedObject.find_resource().

```
======================================================================
ERROR: test_pruning_annotating (test_curation.CurationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/SYNBICT/test/test_curation.py", line 46, in test_pruning_annotating
    pruned_definition = target_doc.getComponentDefinition('/'.join([HOMESPACE, 'UnnamedPart', '1']))
  File "/SBOL/sbol/document.py", line 305, in getComponentDefinition
    return self.componentDefinitions.get(uri)
  File "/SBOL/sbol/property.py", line 534, in get
    return self.__getitem__(uri)
  File "/SBOL/sbol/property.py", line 443, in __getitem__
    return self.get_uri(id)
  File "/SBOL/sbol/property.py", line 478, in get_uri
    object_store, parent_obj, typedURI=False)
  File "/SBOL/sbol/property.py", line 516, in find_resource
    persistentIdentity = parent_obj.properties[SBOL_PERSISTENT_IDENTITY][0]
IndexError: list index out of range
```

**Comment by tcmitchell** [comment]
That exception wasn't the real problem. The code should never have gotten to that point. The real problem was that the sequence encoding wasn't matching in SYNBICT, which started a cascade of unexpected side effects. 

Sequence.encoding was always cast to a string in the Sequence class. SYNBICT was comparing against the constant `sbol.SBOL_ENCODING_IUPAC`, which is a URIRef. The real fix is to remove the cast to `str` in the Sequence encoding accessor.
