### ISSUE TITLE
urllib3.exceptions.HTTPError: HTTP post request failed with: 500 - b'{}'

### ISSUE THREAD

**Issue by tcmitchell** [llotneb/SBOL#76]
When running etl-to-synbiohub-pipeline 2 unit tests fail with the following traceback:

```
======================================================================
ERROR: setUpClass (tests.test_sbh_submissions.TestBackBuilder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/etl-to-synbiohub-pipeline/tests/test_sbh_submissions.py", line 27, in setUpClass
    test.sbh.submit(test.doc)
  File "/SBOL/sbol/partshop.py", line 197, in submit
    ' - ' + str(response.content))
urllib3.exceptions.HTTPError: HTTP post request failed with: 500 - b'{}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/etl-to-synbiohub-pipeline/tests/test_sbh_submissions.py", line 29, in setUpClass
    test.sbh.submit(test.doc, test.target_collection, 1)
  File "/SBOL/sbol/partshop.py", line 197, in submit
    ' - ' + str(response.content))
urllib3.exceptions.HTTPError: HTTP post request failed with: 500 - b'{}'
```

**Comment by tcmitchell** [comment]
I have added a test case based on the etl-to-synbiohub-pipeline which nicely repeats the error.

We must be tickling SynBioHub in some way to cause it an internal error. The request isn't very complicated.

**Comment by jakebeal** [comment]
Is this bug in SBH also with the C library?

**Comment by tcmitchell** [comment]
> Is this bug in SBH also with the C library?

No. The etl-to-synbiohub-pipeline test works with pySBOL.

**Comment by tcmitchell** [comment]
This was a bug in SynBioHub. A test should still be added to ensure that submit() continues to work in the future.
